### ISSUE TITLE
BeanIO fails to run under Wildfly 24

### ISSUE THREAD

**Issue by garcia-jj** [beanio/beanio#141]
We got the following exception while running BeanIO under Wildfly 24 and Java 11 (Amazon).

```
Caused by: java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
        at org.apache.xerces@2.12.0.SP03//org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:144)
        at __redirected.__DocumentBuilderFactory.setAttribute(__DocumentBuilderFactory.java:125)
        at deployment.siscom.ear//org.beanio.internal.config.xml.XmlMappingReader.createDocumentBuilderFactory(XmlMappingReader.java:116)
        at deployment.siscom.ear//org.beanio.internal.config.xml.XmlMappingReader.<init>(XmlMappingReader.java:50)
        at deployment.siscom.ear//org.beanio.internal.config.xml.XmlConfigurationLoader.<init>(XmlConfigurationLoader.java:34)
        at deployment.siscom.ear//org.beanio.internal.compiler.StreamCompiler.<init>(StreamCompiler.java:48)
        at deployment.siscom.ear//org.beanio.internal.DefaultStreamFactory.init(DefaultStreamFactory.java:48)
        at deployment.siscom.ear//org.beanio.StreamFactory.newInstance(StreamFactory.java:349)

```

Looks like this issue has been introduced at this commit:

https://github.com/beanio/beanio/commit/e0b423cfb80b634da034469750d2ed89e7109438#diff-ba3a25a992f113ca7661353ae2815443a45a19edbea278278cdfa7c797bdd4ecR114

**Comment by bjansen** [comment]
Wildfly might be shipping a version of xerces that is older than the one provided by the JDK: https://stackoverflow.com/questions/58374278/org-xml-sax-saxnotrecognizedexception-property-http-javax-xml-xmlconstants-p

**Comment by garcia-jj** [comment]
The issue has been solved just removing xerces from Wildfly module.

```
<module name="org.apache.xerces" xmlns="urn:jboss:module:1.9">
    <!--resources>
        <resource-root path="xercesImpl-2.12.0.SP03.jar"/>
    </resources-->
    <dependencies>
        <module name="jdk.xml.dom"/>
        <module name="java.xml"/>
    </dependencies>
</module>

```

Thank U @bjansen

**Comment by EduardMukhanov** [comment]
Which file should I add this exception to? This is the file jboss-deployment-structure.xml or some other kind?
