### ISSUE TITLE
Fail to instantiate StreamFactory because of 'http://javax.xml.XMLConstants/property/accessExternalDTD' property is not recognized

### ISSUE THREAD

**Issue by nfalco79** [beanio/beanio#161]
We are using BeansIO to parse and write fixed length files. When we instantiate a StreamFactory.newInstance we got the following error:
```
org.beanio.BeanIOException: Failed to load stream factory implementation class 'org.beanio.internal.DefaultStreamFactory'
	at org.beanio.StreamFactory.newInstance(StreamFactory.java:348)
	at org.beanio.StreamFactory.newInstance(StreamFactory.java:299)
	at BeansIO.test(BeansIO.java:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        ...
Caused by: java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	at org.beanio.internal.config.xml.XmlMappingReader.createDocumentBuilderFactory(XmlMappingReader.java:116)
	at org.beanio.internal.config.xml.XmlMappingReader.<init>(XmlMappingReader.java:50)
	at org.beanio.internal.config.xml.XmlConfigurationLoader.<init>(XmlConfigurationLoader.java:34)
	at org.beanio.internal.compiler.StreamCompiler.<init>(StreamCompiler.java:48)
	at org.beanio.internal.DefaultStreamFactory.init(DefaultStreamFactory.java:43)
	at org.beanio.StreamFactory.newInstance(StreamFactory.java:344)
	... 71 more
```
After a debug why this happens and looking in internet for a solution the reason see to be the xercesImpl jar in the classpath.
Library xerces 2.16 does not support JAXP 1.5 so does not recognise the `http://javax.xml.XMLConstants/property/accessExternalDTD` property.

We use this library configuring the instance programmatically and not through XML configuration file. This means that we do not need an XML parser at all. Since the lookup mechanism of XML parse is delegated to the discovery service of the JVM we are not able to avoid this 
issue unless to modify JVM property that impacts on the whole application.

As you did for classloader to support OSGi use cases it would be great if we could configure how to pass an XML parser to the stream factory. Actually the XML parse is created by the XmlConfigurationLoader as field initialisation and there is not configuration (to turn off XML parsing) neither provide a custom implementation of XmlConfigurationLoader because its interface is org.beanio.**internal**.config.xml.ConfigurationLoader internal.

**Comment by bjansen** [comment]
Hi, thanks for the detailed analysis.

I could also simply catch the exception and move on, those two attributes are set for security reasons: https://rules.sonarsource.com/java/RSPEC-2755/. If those attributes can't be set, it's because the JAXP version is too old, but that doesn't prevent the rest of the `DocumentBuilderFactory` initialization from working as usual.

**Comment by nfalco79** [comment]
Thanks very much, let me know when you release so we can integrate the 3.0.1 version and proceed to release our application.

**Comment by bjansen** [comment]
@nfalco79 version 3.0.1 has been published on Sonatype OSS and is on its way to Central :)
